#!/bin/bash

################
## SSH keys.
##
## https://help.ubuntu.com/community/AdvancedOpenSSH
## http://ubuntuforums.org/showthread.php?t=205483
################

##server_name="sd-dummy"
key_size="16384"

. ../common/fwk.sh "client-side" "../client/log" "client-gen-key.log"

begin_block "Generating $key_size ssh keys"
ssh-keygen -t rsa -b $key_size -C "Generated by $(product_name)" -O clear -O permit-user-rc
end_block "Generating $key_size ssh keys. Done"